In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_csv('DATABARANG.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(x)

[['Mouse' 30 12000]
 ['Keyboard' 70 20000]
 ['Monitor ' 75 1500000]
 ['VGA' 82 2400000]
 ['Prosesor AMD' 35 2730000]
 ['Prosesor Intel' 67 3120000]
 ['PSU Cooler Master' 93 1000000]
 ['RAM ' 100 845000]]


In [5]:
print(y)

['No' 'Yes' 'Yes' 'Yes' 'No' 'No' 'Yes' 'No']


In [6]:
from sklearn.impute import SimpleImputer
impute = SimpleImputer(missing_values=np.nan, strategy='mean')
impute.fit(x[:, 1:3])
x[:, 1:3] = impute.transform(x[:, 1:3])

In [7]:
print(x)

[['Mouse' 30.0 12000.0]
 ['Keyboard' 70.0 20000.0]
 ['Monitor ' 75.0 1500000.0]
 ['VGA' 82.0 2400000.0]
 ['Prosesor AMD' 35.0 2730000.0]
 ['Prosesor Intel' 67.0 3120000.0]
 ['PSU Cooler Master' 93.0 1000000.0]
 ['RAM ' 100.0 845000.0]]


In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [9]:
print(x)

[[0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 30.0 12000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 70.0 20000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 75.0 1500000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 82.0 2400000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 35.0 2730000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 67.0 3120000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 93.0 1000000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 100.0 845000.0]]


In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [11]:
print(y)

[0 1 1 1 0 0 1 0]


In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [13]:
print(x_train)

[[1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 70.0 20000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 93.0 1000000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 30.0 12000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 35.0 2730000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 82.0 2400000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 67.0 3120000.0]]


In [14]:
print(x_test)

[[0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 100.0 845000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 75.0 1500000.0]]


In [15]:
print(y_train)

[1 1 0 0 1 0]


In [16]:
print(y_test)

[0 1]


In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [18]:
print(x_train)

[[1.0 0.0 0.0 -0.44721359549995787 -0.44721359549995787
  -0.44721359549995787 0.0 -0.4472135954999579 0.3103823549641963
  -1.2079175403521945]
 [0.0 0.0 0.0 2.2360679774997894 -0.44721359549995787
  -0.44721359549995787 0.0 -0.4472135954999579 1.306493168570222
  -0.4326986866880487]
 [0.0 0.0 1.0 -0.44721359549995787 -0.44721359549995787
  -0.44721359549995787 0.0 -0.4472135954999579 -1.4219842773941092
  -1.214245857524963]
 [0.0 0.0 0.0 -0.44721359549995787 2.2360679774997894
  -0.44721359549995787 0.0 -0.4472135954999579 -1.205438448349321
  0.9357999019231473]
 [0.0 0.0 0.0 -0.44721359549995787 -0.44721359549995787
  -0.44721359549995787 0.0 2.23606797749979 0.8300923446716879
  0.6747568185464452]
 [0.0 0.0 0.0 -0.44721359549995787 -0.44721359549995787
  2.2360679774997894 0.0 -0.4472135954999579 0.18045485753732338
  1.2443053640956134]]


In [19]:
print(x_test)

[[0.0 0.0 0.0 -0.44721359549995787 -0.44721359549995787
  -0.44721359549995787 1.0 -0.4472135954999579 1.6096573292329255
  -0.5553098319104391]
 [0.0 1.0 0.0 -0.44721359549995787 -0.44721359549995787
  -0.44721359549995787 0.0 -0.4472135954999579 0.5269281840089844
  -0.03717886339001515]]
